### ISSUE TITLE
How can I visualize what Jetson is thinking?

### ISSUE THREAD

**Issue by mscribe** [NVIDIA-Jetson/redtail#10]
Around 36 seconds into [this YouTube Video](https://www.youtube.com/watch?v=4_TmPA-qw9U), you can see green, yellow and red shading on top of the video feed.  How would I go about replicating that?  I'm using gstreamer on my laptop to watch what the drone sees, and have the TrailNet DNN node running.  Were you able to see that in real time, or did you apply that effect after the flight was over?

**Comment by Alexey-Kamenev** [comment]
I have added some details in our [wiki](../wiki/Training-TrailNet-model#visualize-dnn-outputs). We haven't shared the deconvnet and scripts that we used to create visualizations as they were not exactly easy to use. DIGITS visualization feature described in our wiki allows for good enough debugging so we decided not to bother. We did the post-processing offline as TensorRT did not support deconv layers at that time (it does support it now) but in theory it should be able to run online (though now you would be potentially running 3 DNNs on a Jetson).
