### ISSUE TITLE
Grammatical errors in the documentation README.md 

### ISSUE THREAD

**Issue by rahuldave2005** [NVIDIA-Jetson/redtail#162]
I noticed a few grammatical errors in the documentation that could be improved for better readability and clarity. Below are some of the areas where corrections are needed
I would be happy to fix these errors and submit a pull request

**Comment by Alexey-Kamenev** [comment]
Thank you for your interest in the project.
This project is inactive, in read-only mode. Please consider contributing to any of its forks instead.
