### ISSUE TITLE
Please include labels_map.txt

### ISSUE THREAD

**Issue by mscribe** [NVIDIA-Jetson/redtail#22]
I ran [idsia_trails_dataset_digits.py](https://github.com/NVIDIA-Jetson/redtail/blob/master/models/dataset/idsia_trails_dataset_digits.py), which created train_map.txt and val_map.txt.  How can I get my hands on labels_map.txt as seen in the image found [here](https://github.com/NVIDIA-Jetson/redtail/wiki/Datasets)?

![NVIDIA DIGITS](https://github.com/NVIDIA-Jetson/redtail/wiki/images/digits_trails_dataset.png "NVIDIA DIGITS")

**Comment by mscribe** [comment]
I noticed inside the CIFAR-10 demo, that labels.txt was simply a list of human readable text labels that mapped to numeric values in train.txt in a zero-based manner.  So, I created the following labels_map.txt for ForestTrails with the following contents:
```
lc
sc
rc
```
I also squashed the images to 320x180 when creating the dataset, based on what I saw in the model training instruction screenshots.

**Comment by Alexey-Kamenev** [comment]
Yes, you are correct, it's just a simple text file that maps label indices to names. Pushed with 37ba895.

**Comment by mscribe** [comment]
Thanks for the quick response!
