### ISSUE TITLE
Where did the file "labels_map.txt" come from? 

### ISSUE THREAD

**Issue by Wenlong0605** [NVIDIA-Jetson/redtail#35]
Hello,thank you for sharing the code. I am very interested in the works what you have done. When I follow the steps to create a training dataset, I couldn't find the way to create the file "labels_map.txt". Could you tell me how to create the file.

**Comment by Alexey-Kamenev** [comment]
It's [here](../tree/master/models/dataset) and it's called `label_map.txt`.

**Comment by Alexey-Kamenev** [comment]
Closing, feel free to re-open or create a new one.
