### ISSUE TITLE
Source for 900Kv motor or idea for replacment

### ISSUE THREAD

**Issue by jtryan** [NVIDIA-Jetson/redtail#57]
TBS doesn't seem to carry the 900Kv motors anymore. Do you have a source or a suggestion for a different motor?

**Comment by nsmoly** [comment]
I think you can use Luminier motors like this:
https://www.getfpv.com/fm2216-11-900kv.html?utm_source=google&utm_medium=cpc&adpos=1o1&scid=scplp1131&sc_intid=1131&gclid=EAIaIQobChMI3b6M66WG2wIVldlkCh3WuQ1mEAYYASABEgKRxfD_BwE
