### ISSUE TITLE
IRIS+ issues and is it better to switch to other platform?

### ISSUE THREAD

**Issue by mkaidrone** [NVIDIA-Jetson/redtail#64]
Hi,
   I have noticed IRIS+ behaves erratically sometimes e.g. It drifts away or flips on takeoff and some of them related to issues with pixhawk. Example, flying away as mentioned here is related to Pixhawk HW issue, https://diydrones.com/group/iris/forum/topics/iris-flyaway-due-to-gyro-offset-drift. Wondering if you have noticed these kinds of issues with redtail experiment. Is it better to switch to some other platform like TBS Discovery, which is using different controller?

Thanks!

**Comment by Alexey-Kamenev** [comment]
Closing the issue, feel free to re-open or create a new one.
