### ISSUE TITLE
Could not get gstreamer sample.

### ISSUE THREAD

**Issue by mattgorski** [NVIDIA-Jetson/redtail#71]
I am trying to test the camera node and I have tried to adjust the variables and the gscam examples will launch but everything.lauch and command line launch fails with: 

Could not get gstreamer sample.

I can launch manually using instructions here from examples changing ffmpegcolorspace to videoconvert

https://github.com/ros-drivers/gscam/issues/25

EDIT: Let me also add that I am testing functions with the internal omnivision camera.

**Comment by mattgorski** [comment]
Well i bypassed the issue and im not even sure it is the correct way but here is what i changed in everything.launch

changed v4l2src to nvcamerasrc

<env name="GSCAM_CONFIG" value="nvcamerasrc

**Comment by Alexey-Kamenev** [comment]
What camera are you using? If it's the one that comes with Jetson devboard then we recommend using some other (USB) camera instead.
You can get this error even with USB cameras though - usually in case the camera does not support the resolution specified in GStreamer pipeline (width, height). You can use [v4l2-ctl](https://www.mankier.com/1/v4l2-ctl) utility to get information about the camera.

**Comment by mattgorski** [comment]
This was solved by using a standard v4l2 UVC camera instead of onboard camera.  You can close this issue.  Thanks for the absolutely fantastic Wiki!

**Comment by ioarun** [comment]
For those of you who still get this error, make these changes in your `v4l.launch` file.  Set `GST10` argument to `true` and replace  ` <param if="$(arg GST10)" name="gscam_config" value="v4l2src device=$(arg DEVICE) ! video/x-raw,format=RGBx,framerate=$(arg FPS) ! ffmpegcolorspace"/>`  with this: `<param if="$(arg GST10)" name="gscam_config" value="v4l2src device=$(arg DEVICE) ! video/x-raw,framerate=$(arg FPS) ! videoconvert "/>`


PS -  Thanks to Michael @meee1 & Sid @bugobliterator to help me with this.
