### ISSUE TITLE
Unable to take Camera feeds

### ISSUE THREAD

**Issue by Chandan1002** [NVIDIA-Jetson/redtail#76]
I have built the project without errors. However, my gscam node is not interacting to Mavros node. 

![ros graph-2](https://user-images.githubusercontent.com/25182454/43336200-208485be-9196-11e8-8f76-f34b1793bf0a.png)
____________________________________________________________________________________________________________
![ros graph](https://user-images.githubusercontent.com/25182454/43336201-20977886-9196-11e8-8a74-4362cea3d3de.png)

It seems that I am unable to get camera feed due to above problem. How do I fix it? Any help will be appreciable.

**Comment by Alexey-Kamenev** [comment]
Closing, feel free to re-open or create a new one.

**Comment by vxgu86** [comment]
trailnet_debug_zed_gscam.launch did not have camera_topic for caffe_ros, is this a problem?
 causing I could not get camera window working in rviz
