### ISSUE TITLE
Can't run Gazebo in simulator

### ISSUE THREAD

**Issue by daylanc** [NVIDIA-Jetson/redtail#87]
@Alexey-Kamenev, I'm following your "Testing in Simulator" tutorial. I get to the part where I test "Running Gazebo simulator". I run the command:
make posix_sitl_default gazebo
In the terminal, it looks like it is running, but the Gazebo GUI does not pop up. I do have nvidia docker V2 installed because I could not install version 1. Is this the issue? Do I need to purge nvidia docker V2 and install V1?

**Comment by Alexey-Kamenev** [comment]
AFAIR, Gazebo should run in v2 as well. What happens if you run any other GUI apps (e.g. VSCode) from the container?

**Comment by kidtronnix** [comment]
This happened to me.

I found this fix in #46
