### ISSUE TITLE
Incorrect TensorRT version in wiki

### ISSUE THREAD

**Issue by kidtronnix** [NVIDIA-Jetson/redtail#96]
This page in the wiki incorrectly tells people to...

`Make sure to download TensorRT 3.0.4 for Ubuntu 16.04 and CUDA 9.0 tar package.`

In fact it should be TensorRT 4.0.1.6 for Ubuntu 16.04 and CUDA 9.0.

**Comment by Alexey-Kamenev** [comment]
Updated, thank you!
